### ISSUE TITLE
tag_indent "<li" also matches "<link"

### ISSUE THREAD

**Issue by thezanke** [rareyman/HTMLBeautify#22]
Having `"...|<li|..."` in tag_indent also matches `"<link"` which is messing up the formatting by adding an extra indent. Work-around-able by using link as a void tag `"<link />"` however that is not exactly html5 compliant. I have switched `"...|<li|..."` to be `"...|<li |<li>|..."` in tag_indent but I'm not extremely happy with it. (It does seem to work, however).

**Comment by rareyman** [comment]
Check 0.85 and see if that solves your issue. (Temporarily disable your custom settings to test.) Let me know how it turns out! :)
