### ISSUE TITLE
Ignored tags aren't actually ignored

### ISSUE THREAD

**Issue by dpcasady** [rareyman/HTMLBeautify#23]
When running HTMLBeautify on the HTMLBeautifyTest.html file, with only the default settings, script and style tags are not actually ignored as they should be. Here are the settings that should ignore these elements:

```
"ignored_tag_opening" : "<script|<style|<!--|{\\*|<\\?php",
"ignored_tag_closing" : "</script|</style|-->|\\*}|\\?>",
```

And in the beautified HTMLBeautifyTest.html here are the results:

``` html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>  </title>
        <link href="css/master.css" rel="stylesheet" type="text/css" media="all" />
        <link href="css/master.css" rel="stylesheet" type="text/css" media="all"> <!-- using non-xhtml style -->
        <meta />
        <style type="text/css" media="screen">
        /* code comment */
        this.code { is: ignored; }
        see.settings {
        to: see-why;
        }
        </style>
    </head>
    <body>
        <div class="sample">
            <script type="text/javascript">
            jQuery(document).ready(function() { // code comment
            indenting(here) { is_not_touched; }
            use_other(plugins){
            to_reformat(different_languages)
            }
            });
            </script>
...
```

Shouldn't these blocks just be completely ignored?

I'm using Sublime Text 3 and HTMLBeautify from Package Control, looks like v0.82.

**Comment by rareyman** [comment]
The contents of the `<style>` and `<script>` tags *are* ignored.

The tags themselves are in the hierarchy defined by the parent or previous element. The script then leaves the content of the tags alone.

For example, the `<style>` tag is on the same level as the other tags inside of the `<head>` tag, since those tags are not parent objects.

The one exception to this is the `<pre>` tag, which I pull out of the hierarchy altogether to avoid rendering issues. If you would like the `<style>` and `<script>` tags to follow this behavior, perhaps we can create a new setting (`"flatten_tag_opening"`?) that designates that the tag *and* contents should be removed from the flow altogether…?

Anyway, let me know what you think! :)

**Comment by dpcasady** [comment]
Thanks for getting back so quickly!

Maybe I'm confused by the expected functionality. I'm definitely all for indenting the tags themselves to align with the hierarchy; I just thought that if the contents were ignored, they wouldn't be aligned to the same indentation of the opening `<script>` or `<style>` tag, but instead left alone to where they were originally. So instead of the result above, I was expecting something more along the lines of the following:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>  </title>
        <link href="css/master.css" rel="stylesheet" type="text/css" media="all" />
        <link href="css/master.css" rel="stylesheet" type="text/css" media="all"> <!-- using non-xhtml style -->
        <meta />
        <style type="text/css" media="screen">
            /* code comment */
                this.code { is: ignored; }
                        see.settings {
                            to: see-why;
                        }
        </style>
    </head>
    <body>
        <div class="sample">
            <script type="text/javascript">
                jQuery(document).ready(function() { // code comment
                            indenting(here) { is_not_touched; }
                                use_other(plugins){
                                    to_reformat(different_languages)
                            }
                });
            </script>
...
```
Does that make sense?

**Comment by rareyman** [comment]
Aha! I think I see the issue… You are using spaces for indentation, yes? When that setting is on, the contents **do** appear to be flatten. (Using tabs does not…) I will look into this!

**Comment by dpcasady** [comment]
Ah you're right! Changing the spaces to tabs fixes the issue. It would be great if it could work with spaces too, thanks for looking into it, I appreciate it!

**Comment by rareyman** [comment]
After a quick look at this, it appears it will take a bit of work to accommodate this. When I have a bit more time, I will try and fix this!

In the meantime, here are some lame workarounds: :)
- After executing HTMLBeautify, immediately select the mangled code and reformat using: **Line→ Re-indent** (or other similar method)
- Add `<style` and `<script` to the `tag_raw_flat_opening` setting (added in v0.85) to pull the code to column one. Then manually indent the code block by using: **Line→Indent**

(If anyone else reading this has the time to tackle this, feel free! Just keep me posted. :) )

**Comment by dpcasady** [comment]
Great, thanks for the suggestions! I may also just convert all spaces to tabs, beautify, and then convert back to spaces.

**Comment by rareyman** [comment]
…that works too. :)

**Comment by ctf0** [comment]
@rareyman 
is there away to make the `reindent` cmnd only work inside the `<script>..</script>` tag ? 
,so we can setup an on save hook like
```
"on_pre_save_language":
[
	{
		"command": "html_beautify"
	},
],
"on_post_save_language":
[
	{
		"command": "reindent",
		"args": {"single_line": false},
		"context": [
            {
                "key": "selector",
                "operand": "text.html.basic meta.tag.script.html source.js.embedded.html",
                "operator": "equal"
            }
        ]
	}
]
```

**Comment by rareyman** [comment]
@ctf0 
Theoretically, you could run a script that selects the contents of the <script> tag, then apply the reindent command, to that selection…? http://code.tutsplus.com/tutorials/how-to-create-a-sublime-text-2-plugin--net-22685 Has a section about text selections. That would be one way of approaching this…

**Comment by ctf0** [comment]
is there away to add this feature to the plugin it self ?

**Comment by rareyman** [comment]
@ctf0
I suppose it is possible—but a part of me thinks it is best to keep the script simple and lean to allow it to work in conjunction with other plugins… If I did add this functionality later, I would certainly turn it off by default—so it wasn’t perceived as a destructive, overreaching plugin.

**Comment by ctf0** [comment]
@rareyman yeah yeah ,it actually make more sense as its more of an extension to the original functionality.

**Comment by tkosig** [comment]
Emtpy lines in the content of <script> tags are also removed when "remove_extraline" is set to true.

I would expect that content of ignored tags is not touched at all? Am I mistaken to expect this behaviour?

**Comment by TheSameSon** [comment]
The same problem here, that would be really killer feature if you add this

**Comment by ctf0** [comment]
@rareyman hi again, sorry to bother u 
is there any chance u can make a small script to simply select the `<script>..</script>` and then run the re-indent ?

i tried to make something like a run multiple commands like
`open the search panel > find the open tag > open select until "another package" > add the closing tag > press enter > re-indent` but it just doesnt work 😢
