### ISSUE TITLE
why i cannot find keymap files after i install htmlbeautify to sublime 3?

### ISSUE THREAD

**Issue by chapgaga** [rareyman/HTMLBeautify#28]
is this a bug?

**Comment by rareyman** [comment]
Interesting. I haven't been able to replicate this. Can you describe what happens again? (Sorry for the delay!)

**Comment by rareyman** [comment]
The keymap files are in the `HTMLBeautify.sublime-package` file which should be in your **Installed Packages** folder. These `.sublime-package` files are zip files, so just rename top `.zip` and expand if you want to see the contents.
