### ISSUE TITLE
AREA tags not treated as self-closing

### ISSUE THREAD

**Issue by mattsnowky** [rareyman/HTMLBeautify#30]
AREA tags not treated as self-closing. They indent, rather than drop to the next line.
![screenshot-1432234735-at-1x-zoom](https://cloud.githubusercontent.com/assets/5940862/7756556/fd699396-ffc9-11e4-9f64-43c096c190cc.png)

**Comment by rareyman** [comment]
Ah, good catch. I will add this to the default settings soon. In the meantime, you can add the `area` tag to your User settings:
`
	"tag_pos_inline":
	"<area.*>|<area.*/> <area.*\">" // add this group to the existing list of tags that should be considered an inline tag 
`
I hope that helps!

**Comment by mattsnowky** [comment]
Thanks for the quick action!

Can you check that real quick? I'm getting Error trying to parse settings: Unexpected trailing characters in Packages/User/HTMLBeautify.sublime-settings:1:17

**Comment by rareyman** [comment]
The Settings file is JSON, so it needs to start and end with a bracket. Then, inside the brackets, you define database pairs like so:

```JSON
{
"ignored_tag_opening" : "<script|<style|<!--|<\\?php",
 "tag_pos_inline":
	"<area.*>|<link.*/>|<link.*\">|<link.*>|<meta.*/>|<script.*</script>|<div.*</div>|<a.*</a>|<li.*</li>|<dt.*</dt>|<dd.*</dd>|<th.*</th>|<td.*</td>|<legend.*</legend>|<label.*</label>|<option.*</option>|<input.*/>|<input.*\">|<span.*</span>|<p.*</p>|<path.*/>|<!--.*-->"
}
```

*(Note that after each pair, a comma is required, except for the last item.)*

You can open the default HTMLBeautify settings file to take a peek at the other options. My guess is that your User settings file isn't set up correctly which is causing the error.

A strategy many people use is to take the contents of the default settings file, and copy-paste it to the the user settings file, then make desired edits. When there are new updates, the user settings file is not touched, meaning any edits you make are not obliterated.

HTH!

**Comment by mattsnowky** [comment]
Check. Totally helps (and works!). Just switched from Brackets to Sublime today. Was annoyed at how poorly Brackets performs with just a few thousand lines. Freezes completely. Not getting that with Sublime.

I'll be digging in more and more now. Thanks for the help!

**Comment by rareyman** [comment]
@mattsnowky Absolutely! I've tested a few other editors and Atom (by GitHub) comes close to Sublime Text, but it isn't quite as reliable or solid as Sublime. :) I also recommend Emmet and CSSLint/CSSComb for some cool web dev packages. Good luck and enjoy!
