### ISSUE TITLE
Custom ignore tags do not work

### ISSUE THREAD

**Issue by ioncube** [rareyman/HTMLBeautify#32]
This may relate to #23, but I'm not sure. Adding {# and #} (volt comment syntax) to the set of ignored tags has no effect, however wrapping such comments with HTML comments, which are also on the list, does work. I read about switching to tags, however this does not resolve and gives the bizarre behaviour of HTML in HTML comments getting indented further and further on each format run :)

**Comment by rareyman** [comment]
Sorry for the late reply. I can't seem to replicate this… Could you reply back with an example? Thanks! :)
