### ISSUE TITLE
Long line support?

### ISSUE THREAD

**Issue by frumbert** [rareyman/HTMLBeautify#33]
I'm actually trying to inminify html, so there are long lines (for instance, one line is 473797 characters long; my html file is about 7MB). It skips long lines, which is as documented. Is it likely that you will support beautifying long lines, or is there a better solution?
(Sublime OSX build 3083)

**Comment by rareyman** [comment]
Wow, 473,000 characters long!

This tool is primarily for developers who have a bit of OCD and want to clean up the indenting of their code. I don't have plans on creating a script that parses through the code and expands and breaks things up into new lines… although I have heard there are some good tools out there—I just don't know any off the top of my head.

Good luck!
