### ISSUE TITLE
Concataned HTML chunk (no spaces, no end-lines) is not beautifed

### ISSUE THREAD

**Issue by op1ekun** [rareyman/HTMLBeautify#35]
I have a chunk of HTML (a div element with a lot of tags inside) from difftool. I pasted it into sublime and used HTMLBeutify. It said it's beautifying the Entire file, but the effect was none. I tried to beautify a selection and the effect was that everything besides the selection was removed.

env:
Windows 10
Sublime 3 (build 3083)
plugin version v2015.02.23.20.05.55

**Comment by op1ekun** [comment]
To add a bit more info. The HTMLPrettify plugin works like a charm with the same chunk of HTML.

**Comment by rareyman** [comment]
Quick reminder: HTMLBeautify assumes that HTML code has been broken up into separate lines before the script has been run. In other words, the script will not work on concatenated code:
```
<!-- HTMLBeautify will not break up code into separate lines -->
<div id="class"><p>Lorem ipsum <strong>dolor</strong>.<ul><li>one</li><li>two</li></ul></p></div>

<!-- HTMLBeautify will reformat this code just fine -->
<div id="class">
<p>Lorem ipsum <strong>dolor</strong>.
<ul>
<li>one</li>
<li>two</li>
</ul>
</p>
</div>
```
…so just to be sure, I want to make sure this is what you are referring to in your original question. If I am mistaken, please let me know and I will try and answer the question. Thanks!

**Comment by op1ekun** [comment]
My bad ... I tottaly missed the comment, and just assumed that it does what I want ;)
It's beautifier, right ;) ?

Sorry for the trouble!

**Comment by rareyman** [comment]
No worries at all! Eventually it would be awesome if that functionality could be added, but for the time being, this seems to work for a lot of people as is, so I am not too worried about it. :) Also. Reason I am hesitant to ever call this 1.0. Heh heh. :)
