### ISSUE TITLE
Best way to handle mixed content with PHP

### ISSUE THREAD

**Issue by SiamKreative** [rareyman/HTMLBeautify#38]
Hi @rareyman 

Thanks for this great ST plugin :) Loving it so far. I have one question though, what's the best way to properly indent a mix of HTML & PHP? Should I simply ignore the PHP tags?

Cheers

**Comment by rareyman** [comment]
Thanks for the kind words!

Yeah, what I usually do is include any custom language tags `<\\?php` in the ignored tag array in the settings file. The script will then skip past those lines until it encounters the proper closing tag `\\?>`, then resume "beautifying". (I believe the <?php tag already exists in the default settings, but you are welcome to experiment with it to taste.)

Also, I find that while **ideally** it is great to "beautify" the whole HTML file, sometimes in practice it is better to just clean up certain chunks of code at a time. (Sort of like the concept of working with components in React.js.) The script allows you to select lines of code and beautify only certain parts of code at a time. Then you can manually move things around and also double check any mixed PHP in there. The script is very rudimentary in that it isn't smart enough to see elements and tags if they are mashed together—it expects elements/tags to be on their own separate line to do it’s magic.

Let me know how it works out! Good luck!

**Comment by SiamKreative** [comment]
Thanks for the super fast response, I really appreciate it. Perhaps it would be a good idea to add this in the docs along with the ignore documentation. Like as example usage of the ignore option :)

I'm now looking to PHP code beautifier, do you recommend one? Do you know one that works well with mixed content?

Ideally, I would like to do a custom key binding that runs both HTMLBeautify & the PHP code beautifier.

**Comment by rareyman** [comment]
Sorry for the late response!

I find that the default command of "re-indent" in ST seems to work pretty well. I haven't had a pressing need for a PHP Beautifier, so I can't recommend a good plug-in. But if you find/found one, let me know! :)

Thanks again and good luck!
