### ISSUE TITLE
Attribute indentation depth configuration?

### ISSUE THREAD

**Issue by saibotsivad** [rareyman/HTMLBeautify#40]
Our work currently uses two tabs to indent attributes, like:

```
<div
		class="pant-size"
		data-whatever="things"
		data-pant-size="36">
	<p>36</p>
</div>
```

Another style I've seen (and we are considering switching to) is no-indentation, like:

```
<div
class="pant-size"
data-whatever="things"
data-pant-size="36">
	<p>36</p>
</div>
```

Unfortunately, HTMLBeautify indents a single tab, which doesn't fit either of these styles.

I looked around in the readme and code, and didn't see a configuration setting for indentation level of attributes. Did I miss it somewhere, or is this not an option yet?

**Comment by rareyman** [comment]
Hi! Thanks for using HTMLBeautify!

Currently there are no settings for indenting or formatting attributes. I like the idea, though. Just brainstorming, but I’m thinking a regex search for the pattern of something="that" could be a way of defining what an attribute is, then have a setting for new lining and indenting it until the element ends.

Anyway, no promises (I’m super busy), but if I have some time I can look into it. Or if someone is reading this and inspired to try implementing it, I’m all for it. :)

**Comment by saibotsivad** [comment]
I'm not familiar at all with python, so I don't think I'll try to implement it.

Thanks for the quick response!
