### ISSUE TITLE
Unbind shortcut

### ISSUE THREAD

**Issue by katerlouis** [rareyman/HTMLBeautify#42]
How can I unbind the shortcut completely? I don't want to bind another sublime-command to it. I use a window resizing tool which uses this shortcut. 

Thanks!

**Comment by rareyman** [comment]
Ah! Good question!

You can override/change the default key mapping by adding an entry in your global keymap file (Read me has more info on this), especially if you don't like the `command-option-shift-f` combination.

However, in your case, you want Sublime to unbind the combo completely so your window resizing tool can use the shortcut. Here are two ways to fix this:

**Add An Entry To Your Keymap**
- In your Default Global Keymap, add the following entry:
<pre>
{
	"keys": ["super+alt+shift+f"],
	"command": "noop",
	"context": [{
		"key": "selector",
		"operator": "equal",
		"operand": "text.html,text.html.twig,text.twig,source.html,source.html.twig,source.twig"
	}]
}
</pre>
- By replacing the `html_beautify` command with `noop` you are telling Sublime to ignore the default keymap and instead execute "no operation".

**Override The Plugin Keymap**
- Browse Packages… to open up your Packages folder
- Create a folder called 'HTMLBeautify'
- In 'HTMLBeautify', create keymap files for all the OSs:
  - Default (Linux).sublime-keymap
  - Default (OSX).sublime-keymap
  - Default (Windows).sublime-keymap
- In the keymap files, paste in the following code:
<pre>
[{
	"keys": ["super+alt+shift+f"],
	"command": "noop",
	"context": [{
		"key": "selector",
		"operator": "equal",
		"operand": "text.html,text.html.twig,text.twig,source.html,source.html.twig,source.twig"
	}]
}]
</pre>

I hope this helps! Good luck!
