### ISSUE TITLE
Colgroup and Caption

### ISSUE THREAD

**Issue by ichintan** [rareyman/HTMLBeautify#43]
Unable to beautify Table Colgroup, col and caption. Try below example.

`<table class="table table-basic">`
`<caption>Caption here</caption>`
`<colgroup>`
`<col class="w-60" />`
`<col class="w-20" />`
`<col class="w-20" />`
`</colgroup>`
`</table>`

**Comment by rareyman** [comment]
It looks like you need to adjust your settings file and add `colgroup` as a tag that you would like to have indented. Like so… (I had trouble with Markdown—doh!)
---
{
        // the contents of these tag blocks will be indented (add/remove as desired)
	"tag_indent":
	"\\{% (if|for|block|else|spaceless)|<html|<head|<body|<div|<a|<nav|<ul|<ol|<dl|<li|<table|<thead|<tbody|<tr|<th|<td|<blockquote|<select|<form|<option|<optgroup|<fieldset|<legend|<label|<header|<section|<aside|<footer|<figure|<video|<span|<p|<g|<svg|<colgroup",
	// this signals when tags should be unindented (see tags above)
	"tag_unindent":
	"\\{% end|</html|</head|</body|</div|</a|</nav|</ul|</ol|</dl|</li|</table|</thead|</tbody|</tr|</th|</td|</blockquote|</select|</form|</option|</optgroup|</fieldset|</legend|</label|</header|</section|</aside|</footer|</figure|</video|</span|</p|</g|</svg|</colgroup",
}
---
I hope that helps!
