### ISSUE TITLE
Custom indentation

### ISSUE THREAD

**Issue by djmtype** [rareyman/HTMLBeautify#46]
This plugin indents using 4 spaces. Is it possible to set to 1 tab character instead?

**Comment by djmtype** [comment]
Nevermind, it's the nature of my document

**Comment by rareyman** [comment]
No problem!

Just to clarify for reference for anyone else reading this—the script uses tab characters, but Sublime Text seems to be smart enough to auto-convert them to spaces or tabs based on your document settings.

**Comment by djmtype** [comment]
Yep! _View > Indentation > (Etc.)_
